# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        # Set up main widget properties
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(600, 800)
        LoginWidget.setMinimumSize(QtCore.QSize(600, 800))
        LoginWidget.setStyleSheet(
            "QWidget#LoginWidget{\n"
            "  background-color: #F9FAFB;\n"
            "}\n"
            "\n"
            "QLineEdit#passwordLineEdit {\n"
            "  border: 1px solid #E5E7EB;\n"
            "  border-radius: 8px;\n"
            "  padding: 12px;\n"
            "  font-size: 16px;\n"
            "  color: #111827;\n"
            "}\n"
            "QToolButton#passwordToggleButton{\n"
            "  border: none;\n"
            "  padding: 0 10px;\n"
            "}\n"
        )

        # Main horizontal layout for centering the content
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(LoginWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # Left spacer for centering
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)

        # Content widget (holds all login UI elements)
        self.contentWidget = QtWidgets.QWidget(LoginWidget)
        self.contentWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.contentWidget.setMaximumSize(QtCore.QSize(420, 420))
        self.contentWidget.setObjectName("contentWidget")

        # Vertical layout for content
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Logo label
        self.logoLabel = QtWidgets.QLabel(self.contentWidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(300, 80))
        self.logoLabel.setStyleSheet(
            "QLabel#logoLabel {\n"
            "    background-color: #E5E7EB;\n"
            "    border-radius: 8px;\n"
            "}\n"
        )
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_2.addWidget(self.logoLabel)

        # Title label
        self.titleLabel = QtWidgets.QLabel(self.contentWidget)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet(
            "QLabel#titleLabel{\n"
            "  color: #111827;\n"
            "}\n"
        )
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)

        # Username label
        self.usernameLabel = QtWidgets.QLabel(self.contentWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_2.addWidget(self.usernameLabel)

        # Username input
        self.usernameLineEdit = QtWidgets.QLineEdit(self.contentWidget)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(0, 48))
        self.usernameLineEdit.setStyleSheet(
            "QLineEdit#usernameLineEdit {\n"
            "  border: 1px solid #E5E7EB;\n"
            "  border-radius: 8px;\n"
            "  background-color: #FFFFFF;\n"
            "  padding: 12px;\n"
            "  font-size: 16px;\n"
            "  color: #111827;\n"
            "}\n"
        )
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout_2.addWidget(self.usernameLineEdit)

        # Password label
        self.passwordLabel = QtWidgets.QLabel(self.contentWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_2.addWidget(self.passwordLabel)

        # Password input with embedded eye icon
        self.passwordLineEdit = QtWidgets.QLineEdit(self.contentWidget)
        self.passwordLineEdit.setPlaceholderText("Enter password")
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 48))
        self.passwordLineEdit.setStyleSheet(
            "QLineEdit#passwordLineEdit {\n"
            "  border: 1px solid #E5E7EB;\n"
            "  border-radius: 8px;\n"
            "  background-color: #FFFFFF;\n"
            "  padding: 12px;\n"
            "  font-size: 16px;\n"
            "  color: #111827;\n"
            "}\n"
        )
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")

        # Add the eye toggle action inside QLineEdit
        self.togglePasswordAction = QtWidgets.QAction(self.passwordLineEdit)
        self.togglePasswordAction.setIcon(QtGui.QIcon("eye-off.png"))  # Default: hidden
        self.togglePasswordAction.setCheckable(True)
        self.togglePasswordAction.toggled.connect(self.toggle_password_visibility)
        self.passwordLineEdit.textChanged.connect(self.on_password_text_changed)

        self.verticalLayout_2.addWidget(self.passwordLineEdit)

        # Login button
        self.loginButton = QtWidgets.QPushButton(self.contentWidget)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 52))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet(
            "QPushButton#loginButton {\n"
            "  color: white;\n"
            "  border-radius: 8px;\n"
            "  font-weight: 600;\n"
            "  min-height: 52px;\n"
            "  font-size: 18px;\n"
            "  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #3B82F6, stop:1 #2563EB);\n"
            "}\n"
            "QPushButton#loginButton:hover {\n"
            "  background: #2563EB;\n"
            "}\n"
        )
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton)

        # Add content widget to main layout
        self.horizontalLayout_2.addWidget(self.contentWidget)

        # Right spacer for centering
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)

        # Set up translations and connect slots
        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        """Set widget text and placeholders"""
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "GST Billing Software"))
        self.logoLabel.setText(_translate("LoginWidget", "Logo"))
        self.titleLabel.setText(_translate("LoginWidget", "GST Billing Software"))
        self.usernameLabel.setText(_translate("LoginWidget", "Username"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginWidget", "Enter username"))
        self.passwordLabel.setText(_translate("LoginWidget", "Password"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginWidget", "Enter password"))
        self.loginButton.setText(_translate("LoginWidget", "Login"))

    def on_password_text_changed(self, text):
        """Show eye icon only when there is text in the password box"""
        if text:  # If not empty, add the action if not already present
            if self.togglePasswordAction not in self.passwordLineEdit.actions():
                self.passwordLineEdit.addAction(
                    self.togglePasswordAction, QtWidgets.QLineEdit.TrailingPosition
                )
        else:  # If empty, remove the action
            self.passwordLineEdit.removeAction(self.togglePasswordAction)

    def toggle_password_visibility(self, checked):
        """Toggle password visibility and icon"""
        if checked:
            self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
            self.togglePasswordAction.setIcon(QtGui.QIcon("eye.png"))  # Show password
        else:
            self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
            self.togglePasswordAction.setIcon(QtGui.QIcon("eye-off.png"))  # Hide password

# Main entry point for testing the UI
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWidget = QtWidgets.QWidget()
    ui = Ui_LoginWidget()
    ui.setupUi(LoginWidget)
    LoginWidget.show()
    sys.exit(app.exec_())